"""added_price_to_item

Revision ID: ebd9e880ddb1
Revises: a18c9595dd05
Create Date: 2026-01-05 04:08:46.189446

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "ebd9e880ddb1"
down_revision: str | Sequence[str] | None = "a18c9595dd05"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("item", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("price", sa.Integer(), nullable=False, server_default=sa.text("0"))
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("item", schema=None) as batch_op:
        batch_op.drop_column("price")

    # ### end Alembic commands ###
